Repository PolymeshAssociation/Polymesh, pull requests merged in 2020-12, with the labels that each got.

#778 Committee: embed `DispatchResult` in `Executed`
  pallets/committee/src/lib.rs
  pallets/runtime/tests/src/committee_test.rs
Labels: merge-after-ci

#777 Patch: Remove tombstone deposit
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
Labels: merge-after-ci

#722 Mesh 1296/pips benchmarks
  Cargo.lock
  pallets/committee/src/lib.rs
  pallets/common/src/traits/governance_group.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/benchmarking.rs
  pallets/pips/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_pips.rs
Labels: merge-after-ci

#766 PTM: Patch for the panic in math operations
  contracts/PercentageTransferManager/Cargo.toml
  contracts/PercentageTransferManager/src/lib.rs
Labels: merge-after-ci

#776 Fix schema for protocol fees
  polymesh_schema.json
Labels: merge-after-ci

#779 Add snapshot details to events when snapshot is created
  pallets/pips/src/lib.rs
Labels: merge-after-ci

#782 Remove already executed runtime storage code
  pallets/pips/src/lib.rs
Labels: merge-after-ci

#783 MESH-1388: Reduce chain-spec duplication
  Cargo.lock
  Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  src/chain_spec.rs
Labels: merge-after-ci

#784 Pips: Misc cleanup
  pallets/pips/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
Labels: merge-after-ci

#785 MESH-1399: Declaration Date for Corporate Actions
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  polymesh_schema.json
Labels: breaking-api-changes, merge-after-ci

#787 MESH-1366: Nix unused error variants
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/contracts/src/lib.rs
  pallets/corporate-actions/src/distribution.rs
  pallets/corporate-actions/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/im-online/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/common/src/sto_capped.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/settlement/src/lib.rs
  pallets/staking/src/lib.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#786 Minor fixes
  pallets/identity/src/lib.rs
  pallets/im-online/src/lib.rs
  pallets/im-online/src/mock.rs
  pallets/permissions/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  polymesh_schema.json
Labels: merge-after-ci

#788 pips and identity benchmark fixes
  pallets/identity/src/benchmarking.rs
  pallets/pips/src/benchmarking.rs
Labels: merge-after-ci

#790 Minor fixes and added benchmarks build to CI
  .circleci/config.yml
  Cargo.lock
  pallets/common/src/constants.rs
  pallets/contracts/src/benchmarking.rs
  pallets/identity/Cargo.toml
  pallets/identity/src/benchmarking.rs
  pallets/pips/src/benchmarking.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  polymesh_schema.json
  rpc/runtime-api/src/pips.rs
Labels: merge-after-ci

#793 More minor fixes
  .circleci/config.yml
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
Labels: breaking-api-changes

#795 Backporting some minor fixes to tooling
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
Labels: merge-after-ci

#796 Mesh 1400/update storage hashers
  pallets/asset/src/checkpoint.rs
  pallets/asset/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/confidential/src/lib.rs
  pallets/corporate-actions/src/ballot.rs
  pallets/corporate-actions/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#804 Use mocked InvestorUid from crypto
  pallets/identity/src/lib.rs
  pallets/identity/src/migration.rs
  pallets/runtime/develop/src/runtime.rs
Labels: merge-after-ci

#803 Use cryptography's new crate structure
  Cargo.lock
  pallets/confidential/Cargo.toml
  pallets/confidential/src/lib.rs
  pallets/identity/Cargo.toml
  pallets/identity/src/lib.rs
  pallets/identity/src/migration.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/storage.rs
  primitives/Cargo.toml
  primitives/src/cdd_id.rs
  primitives/src/investor_zkproof_data.rs
  primitives/src/lib.rs
  primitives/src/valid_proof_of_investor.rs
Labels: merge-after-ci

#807 MESH-1423, MESH-1424, MESH-1425 - Sto and settlement fixes
  pallets/runtime/tests/src/sto_test.rs
  pallets/settlement/src/lib.rs
  pallets/sto/src/lib.rs
  polymesh_schema.json
Labels: merge-after-ci

#812 MESH-1416: Require IU claims for payer and receiver of transfers
  Cargo.lock
  pallets/asset/src/lib.rs
Labels: release-notes

#809 MESH-1409/Add check for zero balance during revoke of IU claim
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/common/src/traits/mod.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/staking/mock.rs
Labels: merge-after-ci, release-notes

#811 MESH-1483: Rename valid_from to trade_date and add value_date
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  pallets/sto/src/lib.rs
  polymesh_schema.json
  scripts/cli/tests/12_A_settlement.js
  scripts/cli/tests/12_B_settlement.js
  scripts/cli/util/init.js
Labels: breaking-api-changes, merge-after-ci, release-notes

#813 bridge transfer script fix
  scripts/cli/package.json
  scripts/cli/tests/10_bridge_transfer.js
Labels: merge-after-ci

#805 MESH-1422: correctly check permissions in batches
  pallets/asset/src/lib.rs
  pallets/permissions/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/utility_test.rs
  pallets/utility/src/lib.rs
  primitives/src/migrate.rs
Labels: merge-after-ci, release-notes, storage-modification-changes

#794 MESH-1387: Corporate Actions Benchmarks
  Cargo.lock
  pallets/asset/src/benchmarking.rs
  pallets/common/src/benchs/mod.rs
  pallets/corporate-actions/Cargo.toml
  pallets/corporate-actions/src/ballot/benchmarking.rs
  pallets/corporate-actions/src/ballot/mod.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_capital_distribution.rs
  pallets/weights/src/pallet_corporate_actions.rs
  pallets/weights/src/pallet_corporate_ballot.rs
Labels: merge-after-ci

#818 MESH-1413: ASCII-only tickers
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/dividend_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/runtime/tests/src/voting_test.rs
Labels: merge-after-ci, release-notes

#820 Fix minor typos
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/testnet/src/fee_details.rs
  polymesh_schema.json
Labels: merge-after-ci, release-notes

#830 Remove `IdentityRole`
  pallets/common/src/traits/identity.rs
  pallets/identity/src/lib.rs
  primitives/src/identity.rs
  primitives/src/identity_role.rs
  primitives/src/lib.rs
  primitives/src/secondary_key.rs
Labels: merge-after-ci

#827 MESH-1433: Introduce limits for fixed values in CA extrinsic weights
  pallets/corporate-actions/src/ballot/mod.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/src/pallet_capital_distribution.rs
  pallets/weights/src/pallet_corporate_actions.rs
  pallets/weights/src/pallet_corporate_ballot.rs
Labels: merge-after-ci, release-notes

#826 Remove STO, Voting, & Dividend
  pallets/asset/src/checkpoint.rs
  pallets/runtime/common/src/dividend.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/common/src/sto_capped.rs
  pallets/runtime/common/src/voting.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/dividend_test.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/voting_test.rs
  polymesh_schema.json
Labels: breaking-api-changes, merge-after-ci, release-notes

#817 MESH-1095/DocumentHash
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  polymesh_schema.json
  primitives/src/document.rs
  primitives/src/document_hash.rs
  primitives/src/lib.rs
  primitives/src/migrate.rs
  src/service.rs
Labels: merge-after-ci, release-notes

#823 Add benchmarks to permissions
  pallets/permissions/Cargo.toml
  pallets/permissions/src/benchmarking.rs
  pallets/permissions/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
Labels: merge-after-ci
