Repository PolymeshAssociation/Polymesh, pull requests merged in 2020-08, with the labels that each got.

#493 mesh-1129 use `TestStorage` & `ExtBuilder` for `transaction_payment_test`.
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/balances_test.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/transaction_payment_test.rs
  pallets/runtime/tests/src/treasury_test.rs
Labels: merge-after-ci

#495 MESH-1116\Clean up clippy lints and cargo warnings
  node-rpc/src/lib.rs
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/confidential/src/lib.rs
  pallets/group/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/common/src/bridge.rs
  pallets/runtime/common/src/cdd_check.rs
  pallets/runtime/common/src/contracts_wrapper.rs
  pallets/runtime/common/src/voting.rs
  pallets/runtime/develop/src/constants.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/fee_details.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/staking/reward-curve/src/lib.rs
  pallets/staking/reward-curve/src/log.rs
  pallets/staking/src/lib.rs
  pallets/staking/src/offchain_election.rs
  pallets/staking/src/slashing.rs
  pallets/transaction-payment/src/lib.rs
  pallets/treasury/src/lib.rs
  pallets/utility/src/lib.rs
  rpc/src/identity.rs
  src/chain_spec.rs
  src/command.rs
  src/service.rs
Labels: merge-after-ci

#510 fix: use correct type for rules
  polymesh_schema.json
Labels: merge-after-ci

#508 DEVOPS-177/Remove-concourse-commit-filters
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/master-commit.yaml
Labels: merge-after-ci

#491 Mesh 1132/Update weight polynomial
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/confidential/src/lib.rs
  pallets/group/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/common/src/bridge.rs
  pallets/runtime/common/src/dividend.rs
  pallets/runtime/common/src/exemption.rs
  pallets/runtime/common/src/sto_capped.rs
  pallets/runtime/common/src/voting.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/Cargo.toml
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/staking/src/lib.rs
  pallets/transaction-payment/src/lib.rs
  pallets/treasury/src/lib.rs
  pallets/utility/src/lib.rs
Labels: merge-after-ci

#509 MESH-1169: rename master and signing keys
  node-rpc/src/lib.rs
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/common/src/context.rs
  pallets/common/src/protocol_fee.rs
  pallets/common/src/traits/identity.rs
  pallets/compliance-manager/src/lib.rs
  pallets/group/src/lib.rs
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/identity/src/types.rs
  pallets/multisig/src/lib.rs
  pallets/runtime/common/src/contracts_wrapper.rs
  pallets/runtime/common/src/dividend.rs
  pallets/runtime/common/src/exemption.rs
  pallets/runtime/common/src/sto_capped.rs
  pallets/runtime/common/src/voting.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/fee_details.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/cdd_offchain_worker/mock.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/multisig.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/runtime/tests/src/storage.rs
  polymesh_schema.json
  primitives/src/authorization.rs
  primitives/src/identity.rs
  primitives/src/lib.rs
  primitives/src/secondary_key.rs
  rpc/runtime-api/src/identity.rs
  rpc/runtime-api/src/pips.rs
  rpc/src/identity.rs
  scripts/cli/README.md
  scripts/cli/index.js
  scripts/cli/src/commands/helpers/identity_helper.ts
  scripts/cli/src/commands/types.ts
  scripts/cli/tests/0_create_identities.js
  scripts/cli/tests/1_poly_transfer.js
  scripts/cli/tests/2_key_management.js
  scripts/cli/tests/3_auth_join_to_did.js
  scripts/cli/tests/4_permission_management.js
  scripts/cli/tests/5_claim_management.js
  scripts/cli/tests/6_create_assets.js
  scripts/cli/tests/7_create_claim_rules.js
  scripts/cli/tests/8_asset_transfer.js
  scripts/cli/tests/9_offchain_worker_test.js
  scripts/cli/util/init.js
  src/chain_spec.rs
  src/service.rs
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#506 pips: bug fix, use `=`, not `+=` to aggregate nays
  pallets/pips/src/lib.rs
Labels: aldebaran-backport-needed, merge-after-ci, storage-modification-changes

#519 Implement Governance v2
  Cargo.lock
  pallets/committee/src/lib.rs
  pallets/common/src/traits/pip.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/lib.rs
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/storage.rs
  polymesh_schema.json
  rpc/runtime-api/src/pips.rs
  scripts/cli/tests/11_governance_management.js
  src/chain_spec.rs
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#501 Mesh 1039/Allow compliance management based on sender/receiver's did
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  polymesh_schema.json
  primitives/src/lib.rs
  primitives/src/predicate/base.rs
  primitives/src/predicate/mod.rs
  primitives/src/predicate/valid_proof_of_investor.rs
  primitives/src/rule.rs
  scripts/cli/tests/8_asset_transfer.js
Labels: breaking-api-changes, merge-after-ci

#522 Remove identity balances
  pallets/balances/src/lib.rs
  pallets/common/src/context.rs
  pallets/common/src/traits/identity.rs
  pallets/common/src/traits/transaction_payment.rs
  pallets/identity/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/testnet-v1/src/fee_details.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/balances_test.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/cdd_offchain_worker/mock.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/fee_details.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/multisig.rs
  pallets/runtime/tests/src/protocol_fee.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/treasury_test.rs
  pallets/runtime/tests/src/utility_test.rs
  pallets/transaction-payment/src/lib.rs
  pallets/treasury/src/lib.rs
  primitives/src/traits.rs
  scripts/cli/index.js
  scripts/cli/src/commands/helpers/balance_helper.ts
  scripts/cli/src/commands/helpers/identity_helper.ts
  scripts/cli/tests/0_create_identities.js
  scripts/cli/tests/10_bridge_transfer.js
  scripts/cli/util/init.js
  src/chain_spec.rs
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#530 Remove compile warnings
  pallets/balances/src/lib.rs
  pallets/common/src/context.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/testnet-v1/src/fee_details.rs
  primitives/src/traits.rs
  src/chain_spec.rs
  src/command.rs
Labels: merge-after-ci

#465 Deprecate direct transfer functions
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/dividend_test.rs
  pallets/runtime/tests/src/statistics_test.rs
  pallets/runtime/tests/src/voting_test.rs
  scripts/cli/tests/8_asset_transfer.js
Labels: merge-after-ci

#536 Simplify `get_latest_rule_id`
  pallets/compliance-manager/src/lib.rs
Labels: merge-after-ci

#531 Add CODEOWNERS for Concourse
  .github/CODEOWNERS
Labels: merge-after-ci

#507 Mesh 1149/QA use cases for settlement
  scripts/cli/package.json
  scripts/cli/tests/12_A_settlement.js
  scripts/cli/tests/12_B_settlement.js
  scripts/cli/util/init.js
  scripts/cli/yarn.lock
Labels: merge-after-ci

#521 MESH-1143: Link bonding POLYX to both staking & governance
  pallets/balances/src/lib.rs
  pallets/common/src/traits/balances.rs
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#524 MESH-1197/Rename treasury_did to primary_issuance_agent
  pallets/asset/src/lib.rs
  pallets/basic-sto/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/common/src/traits/compliance_manager.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  polymesh_schema.json
  primitives/src/authorization.rs
  primitives/src/predicate/base.rs
  primitives/src/predicate/mod.rs
  primitives/src/predicate/valid_proof_of_investor.rs
  primitives/src/rule.rs
  rpc/runtime-api/src/compliance_manager.rs
  rpc/src/compliance_manager.rs
Labels: breaking-api-changes, merge-after-ci

#532 Misc cleanup of identity, etc.
  pallets/common/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/identity_test.rs
Labels: merge-after-ci

#538 balances: fix a typo
  pallets/balances/src/lib.rs
Labels: merge-after-ci

#535 MESH-1213: Add active members limit
  pallets/committee/src/lib.rs
  pallets/common/src/traits/group.rs
  pallets/group/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/group_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  src/chain_spec.rs
Labels: merge-after-ci

#539 removed fee multiplier adjustment
  pallets/transaction-payment/src/lib.rs
Labels: merge-after-ci

#542 Change maximum weight for block
  pallets/runtime/common/src/lib.rs
Labels: merge-after-ci

#534 Mesh 1167/check for rule id
  pallets/compliance-manager/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
Labels: merge-after-ci

#502 Mesh 1133/Examples SE
  Cargo.lock
  contracts/examples/RuntimeInteraction/.gitignore
  contracts/examples/RuntimeInteraction/.ink/abi_gen/Cargo.toml
  contracts/examples/RuntimeInteraction/.ink/abi_gen/main.rs
  contracts/examples/RuntimeInteraction/Cargo.toml
  contracts/examples/RuntimeInteraction/lib.rs
  contracts/examples/custom-ink-env-types/.gitignore
  contracts/examples/custom-ink-env-types/Cargo.toml
  contracts/examples/custom-ink-env-types/src/calls.rs
  contracts/examples/custom-ink-env-types/src/lib.rs
Labels: merge-after-ci

#541 MESH-819: Migrate `Claim::Jurisdiction` to ISO-3166-1 enum
  Cargo.lock
  pallets/compliance-manager/Cargo.toml
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  polymesh_schema.json
  primitives/src/identity_claim.rs
  primitives/src/jurisdiction.rs
  primitives/src/lib.rs
  primitives/src/migrate.rs
  primitives/src/predicate/base.rs
  primitives/src/rule.rs
  primitives_derive/Cargo.toml
  primitives_derive/src/lib.rs
  primitives_derive/src/migrate.rs
Labels: merge-after-ci, storage-modification-changes

#546 MESH-1223: Reserve Classic tickers to systematic DID on genesis
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/ext_builder.rs
  polymesh_schema.json
  src/chain_spec.rs
Labels: merge-after-ci

#554 Devops 173/wasm artifacts
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  .concourse/scripts/t-cargo-build.sh
  .concourse/scripts/t-rustfmt-lint.sh
Labels: merge-after-ci

#555 Mesh 1221/added DTI as an asset identifier
  pallets/asset/src/lib.rs
  polymesh_schema.json
Labels: merge-after-ci

#559 MESH-1225: define `Utility::{batch_atomic, batch_optimistic}`
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/utility_test.rs
  pallets/utility/src/lib.rs
Labels: merge-after-ci

#547 MESH-1224: Impl migration process for ST20 Classic tokens to Polymesh
  Cargo.lock
  pallets/asset/Cargo.toml
  pallets/asset/src/ethereum.rs
  pallets/asset/src/lib.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  polymesh_schema.json
Labels: merge-after-ci

#564 DEVOPS-194/pipeline_artifact_bugfix
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/tooling-pull-request.yaml
Labels: merge-after-ci

#556 MESH-1227: Waive `ProtocolOp::AssetCreateAsset` if `classic_ticker.is_created`
  Cargo.lock
  pallets/asset/Cargo.toml
  pallets/asset/src/lib.rs
  pallets/common/src/protocol_fee.rs
  pallets/identity/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/protocol_fee.rs
Labels: merge-after-ci

#557 Mesh 1174/add usage fee mvp
  pallets/asset/src/lib.rs
  pallets/contracts/src/lib.rs
  pallets/runtime/tests/src/contract_test.rs
  polymesh_schema.json
  primitives/src/lib.rs
  primitives/src/smart_extension.rs
Labels: merge-after-ci

#572 MESH-1233/Rebase-Fees
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet-v1/src/runtime.rs
Labels: merge-after-ci

#558 MESH-1232/Remove smart extension api
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
Labels: merge-after-ci

#571 Mesh 1179/add clippy to CI
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/master-commit.yaml
  .concourse/pipelines/master-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  .concourse/scripts/t-clippy-test.sh
Labels: concourse-test

#575 MESH-1228: Rename `testnet-v1` to `testnet`
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  .concourse/scripts/t-cargo-build.sh
  Cargo.lock
  Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/build.rs
  pallets/runtime/testnet/src/constants.rs
  pallets/runtime/testnet/src/fee_details.rs
  pallets/runtime/testnet/src/lib.rs
  pallets/runtime/testnet/src/runtime.rs
  src/chain_spec.rs
  src/command.rs
  src/service.rs
Labels: concourse-test-mesh1228
