Repository PolymeshAssociation/Polymesh, pull requests merged in 2020-10, with the labels that each got.

#648 MESH-1264: Moved bridge to a new pallet
  Cargo.lock
  Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/bridge/src/lib.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/fee_details.rs
  pallets/runtime/testnet/src/lib.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/storage.rs
Labels: merge-after-ci

#647 Added a wrapper function for mock cdd
  pallets/identity/src/lib.rs
Labels: merge-after-ci

#659 Move to `develop` cryptography branch, and generalise scopes
  Cargo.lock
  pallets/confidential/Cargo.toml
  pallets/identity/Cargo.toml
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/storage.rs
  polymesh_schema.json
  primitives/Cargo.toml
  primitives/src/investor_zkproof_data.rs
  primitives/src/valid_proof_of_investor.rs
Labels: merge-after-ci

#657 Updated transfer event to use portfolios
  pallets/asset/src/lib.rs
Labels: merge-after-ci

#632 MESH-1268/refactor cli tests
  scripts/cli/package.json
  scripts/cli/tests/0_create_identities.js
  scripts/cli/tests/10_bridge_transfer.js
  scripts/cli/tests/11_governance_management.js
  scripts/cli/tests/12_A_settlement.js
  scripts/cli/tests/12_B_settlement.js
  scripts/cli/tests/1_poly_transfer.js
  scripts/cli/tests/2_key_management.js
  scripts/cli/tests/3_auth_join_to_did.js
  scripts/cli/tests/4_permission_management.js
  scripts/cli/tests/5_claim_management.js
  scripts/cli/tests/6_create_assets.js
  scripts/cli/tests/7_create_claim_compliance.js
  scripts/cli/tests/8_asset_transfer.js
  scripts/cli/util/init.js
  scripts/cli/yarn.lock
Labels: merge-after-ci

#661 Remove governance v2 from tooling branch
  Cargo.lock
  pallets/balances/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/common/src/traits/balances.rs
  pallets/common/src/traits/group.rs
  pallets/common/src/traits/pip.rs
  pallets/group/src/lib.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/lib.rs
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/group_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/runtime/tests/src/storage.rs
  pallets/staking/src/lib.rs
  polymesh_schema.json
  rpc/runtime-api/src/pips.rs
  scripts/cli/tests/11_governance_management.js
  src/chain_spec.rs
Labels: merge-after-ci

#639 Introduce wrapper contracts pallet In develop
  Cargo.lock
  Cargo.toml
  contracts/CountTransferManager/.ink/abi_gen/Cargo.toml
  contracts/CountTransferManager/.ink/abi_gen/main.rs
  contracts/CountTransferManager/Cargo.lock
  contracts/CountTransferManager/Cargo.toml
  contracts/CountTransferManager/lib.rs
  contracts/PercentageTransferManager/.ink/abi_gen/Cargo.toml
  contracts/PercentageTransferManager/.ink/abi_gen/main.rs
  contracts/PercentageTransferManager/Cargo.toml
  contracts/PercentageTransferManager/src/lib.rs
  node-rpc/Cargo.toml
  pallets/asset/Cargo.toml
  pallets/asset/src/lib.rs
  pallets/cdd-offchain-worker/Cargo.toml
  pallets/common/src/protocol_fee.rs
  pallets/common/src/traits/identity.rs
  pallets/contracts/Cargo.toml
  pallets/contracts/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/common/src/contracts_wrapper.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/lib.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/fixtures/flipper.wat
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/contract_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/Cargo.toml
  polymesh_schema.json
  primitives/src/lib.rs
  primitives/src/smart_extension.rs
  rust-toolchain
  src/chain_spec.rs
  utils/wasm-builder/Cargo.toml
Labels: merge-after-ci

#658 MESH-1280: Substrate 2.0.0-rc6 => 2.0.0
  Cargo.lock
  Cargo.toml
  bin/bench/Cargo.toml
  bin/executor/Cargo.toml
  bin/testing/Cargo.toml
  contracts/examples/custom-ink-env-types/Cargo.toml
  node-rpc/Cargo.toml
  node-rpc/src/lib.rs
  pallets/asset/Cargo.toml
  pallets/balances/Cargo.toml
  pallets/balances/src/lib.rs
  pallets/basic-sto/Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/cdd-offchain-worker/Cargo.toml
  pallets/committee/Cargo.toml
  pallets/common/Cargo.toml
  pallets/common/src/traits/balances.rs
  pallets/compliance-manager/Cargo.toml
  pallets/confidential/Cargo.toml
  pallets/contracts/Cargo.toml
  pallets/group/Cargo.toml
  pallets/group/rpc/Cargo.toml
  pallets/group/rpc/runtime-api/Cargo.toml
  pallets/identity/Cargo.toml
  pallets/im-online/Cargo.toml
  pallets/multisig/Cargo.toml
  pallets/permissions/Cargo.toml
  pallets/pips/Cargo.toml
  pallets/portfolio/Cargo.toml
  pallets/protocol-fee/Cargo.toml
  pallets/protocol-fee/rpc/Cargo.toml
  pallets/protocol-fee/rpc/runtime-api/Cargo.toml
  pallets/runtime/common/Cargo.toml
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/Cargo.toml
  pallets/staking/Cargo.toml
  pallets/staking/rpc/Cargo.toml
  pallets/staking/rpc/runtime-api/Cargo.toml
  pallets/statistics/Cargo.toml
  pallets/transaction-payment/Cargo.toml
  pallets/treasury/Cargo.toml
  pallets/utility/Cargo.toml
  pallets/weights/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/runtime-api/Cargo.toml
  src/cli.rs
  src/command.rs
  src/service.rs
Labels: merge-after-ci, storage-modification-changes

#662 Prune user auths after instruction execution (settlement)
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/lib.rs
Labels: merge-after-ci

#666 Change InvestorUid to 16 bytes
  bin/testing/src/genesis.rs
  polymesh_schema.json
  primitives/src/cdd_id.rs
Labels: merge-after-ci

#640 Mesh 1168/scheduled checkpoints
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/common/src/protocol_fee.rs
  pallets/identity/src/lib.rs
  pallets/runtime/common/src/dividend.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/voting_test.rs
  polymesh_schema.json
  primitives/Cargo.toml
  primitives/src/calendar.rs
  primitives/src/lib.rs
Labels: merge-after-ci

#665 MESH-1315/ Apply origin permissions in contracts
  pallets/asset/src/lib.rs
  pallets/contracts/src/lib.rs
  pallets/runtime/tests/src/contract_test.rs
Labels: merge-after-ci

#668 MESH-1306
  Cargo.lock
  pallets/contracts/src/lib.rs
Labels: merge-after-ci

#675 Update Jurisdiction enum
  primitives/src/jurisdiction.rs
Labels: merge-after-ci

#663 MESH-1220: Refactor & Optimize compliance manager
  Cargo.lock
  pallets/compliance-manager/Cargo.toml
  pallets/compliance-manager/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  primitives/src/proposition/base.rs
  primitives/src/proposition/mod.rs
  primitives/src/valid_proof_of_investor.rs
Labels: merge-after-ci

#667 [MESH-1260] Added a redeem function
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
Labels: merge-after-ci

#669 Mesh 1323: use of scheduler pallet in bridge
  Cargo.lock
  pallets/bridge/Cargo.toml
  pallets/bridge/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/storage.rs
Labels: merge-after-ci

#674 Mesh 1310/ensure 11_governance_management can be re-run without restarting node
  scripts/cli/package.json
  scripts/cli/tests/11_governance_management.js
  scripts/cli/yarn.lock
Labels: merge-after-ci

#670 MESH-1312/ Simplifies commissions
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/testnet/src/lib.rs
  pallets/staking/src/lib.rs
  src/chain_spec.rs
Labels: merge-after-ci, storage-modification-changes

#677 Simplify compliance_canTransfer RPC
  pallets/asset/src/lib.rs
  pallets/basic-sto/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/compliance-manager/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  polymesh_schema.json
  rpc/runtime-api/src/compliance_manager.rs
  rpc/src/compliance_manager.rs
Labels: merge-after-ci

#676 Rename Authorize to affirm
  pallets/basic-sto/src/lib.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/lib.rs
  polymesh_schema.json
  scripts/cli/tests/12_A_settlement.js
  scripts/cli/tests/12_B_settlement.js
  scripts/cli/util/init.js
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#672 MESH-1314/ [Staking] Permissioned entity
  Cargo.lock
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/runtime/tests/src/storage.rs
  pallets/staking/src/lib.rs
  primitives/src/migrate.rs
  src/chain_spec.rs
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#671 Benchmarks for identity pallet
  Cargo.lock
  pallets/bridge/Cargo.toml
  pallets/committee/src/lib.rs
  pallets/common/src/traits/group.rs
  pallets/common/src/traits/identity.rs
  pallets/group/src/lib.rs
  pallets/identity/Cargo.toml
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/im-online/src/benchmarking.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_identity.rs
  scripts/bench.sh
Labels: merge-after-ci

#681 Remove cdd off-chain worker
  Cargo.lock
  Cargo.toml
  pallets/cdd-offchain-worker/Cargo.toml
  pallets/cdd-offchain-worker/src/lib.rs
  pallets/common/src/traits/mod.rs
  pallets/common/src/traits/offchain.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/cdd_offchain_worker/mock.rs
  pallets/runtime/tests/src/cdd_offchain_worker/mod.rs
  pallets/runtime/tests/src/lib.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#678 MESH-1269: Initiating a Corporate Action
  pallets/asset/src/lib.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/weights/src/pallet_corporate_actions.rs
  polymesh_schema.json
Labels: merge-after-ci

#682 Use local im-online pallet in node-executor
  Cargo.lock
  bin/executor/Cargo.toml
Labels: merge-after-ci

#680 Make PortfolioNumber start from 1 instead of 0
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/portfolio.rs
  primitives/src/identity_id.rs
  primitives/src/secondary_key.rs
Labels: merge-after-ci

#628 MESH-1094/Implement a new PrimaryIssuance pallet which wraps up some of the STO functionality
  Cargo.lock
  Cargo.toml
  pallets/basic-sto/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/basic_sto_test.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/.gitignore
  pallets/settlement/src/lib.rs
  pallets/sto/Cargo.toml
  pallets/sto/src/lib.rs
  polymesh_schema.json
  scripts/cli/package-lock.json
Labels: merge-after-ci

#688 Added support for passing ws provider endpoint via an env variable to the CLI tests
  .circleci/config.yml
  scripts/cli/tests/9_offchain_worker_test.js
  scripts/cli/util/init.js
Labels: merge-after-ci

#687 Mesh 1297/portfolio benchmarks
  .github/workflows/docs.yml
  Cargo.lock
  Cargo.toml
  pallets/identity/src/benchmarking.rs
  pallets/portfolio/Cargo.toml
  pallets/portfolio/src/benchmarking.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_portfolio.rs
  scripts/bench.sh
Labels: merge-after-ci

#693 Clean up TODO comments
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/runtime/common/src/sto_capped.rs
  pallets/staking/src/lib.rs
  polymesh_schema.json
  primitives/src/authorization.rs
  primitives/src/identity.rs
  primitives/src/identity_claim.rs
  src/chain_spec.rs
Labels: merge-after-ci

#685 MESH-1270: Link Documentation to Corporate Actions
  pallets/asset/src/lib.rs
  pallets/corporate-actions/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/staking/src/lib.rs
  pallets/weights/src/pallet_corporate_actions.rs
  polymesh_schema.json
  primitives/src/document.rs
  primitives/src/lib.rs
  primitives/src/migrate.rs
  primitives_derive/src/migrate.rs
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes

#697 Removed bitmasking from IdentityId
  pallets/common/src/lib.rs
  pallets/identity/src/lib.rs
  primitives/src/identity_id.rs
Labels: merge-after-ci

#686 MESH-1326: Use scheduler pallet in settlement
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/Cargo.toml
  pallets/settlement/src/lib.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#689 MESH-1339/ Add switch for Slashing
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
  pallets/staking/src/slashing.rs
  polymesh_schema.json
Labels: merge-after-ci

#694 Mesh 1335/Implicit requirement should not be paused
  pallets/asset/src/lib.rs
  pallets/common/src/constants.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/confidential_test.rs
  polymesh_schema.json
  primitives/src/condition.rs
  primitives/src/proposition/mod.rs
Labels: breaking-api-changes, merge-after-ci

#690 MESH-1226 Review approach to controller transfer
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
Labels: merge-after-ci
