Repository PolymeshAssociation/Polymesh, pull requests merged in 2020-09, with the labels that each got.

#578 MESH-1235/remove batch functions
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/common/src/bridge.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/testnet/src/fee_details.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/identity_test.rs
Labels: merge-after-ci

#579 MESH-1240, MESH-1239, MESH-1238
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
  polymesh_schema.json
Labels: merge-after-ci, storage-modification-changes

#569 MESH-1231: add `get_key_id_data` rpc call
  pallets/identity/src/lib.rs
  pallets/identity/src/types.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  polymesh_schema.json
  rpc/runtime-api/src/identity.rs
  rpc/src/identity.rs
Labels: merge-after-ci

#562 Fix asset RPC
  node-rpc/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  rpc/runtime-api/src/asset.rs
  rpc/src/asset.rs
  src/service.rs
Labels: merge-after-ci

#585 Optimizing JS Scripts
  scripts/cli/tests/0_create_identities.js
  scripts/cli/tests/10_bridge_transfer.js
  scripts/cli/tests/1_poly_transfer.js
  scripts/cli/tests/2_key_management.js
  scripts/cli/tests/3_auth_join_to_did.js
  scripts/cli/tests/4_permission_management.js
  scripts/cli/tests/5_claim_management.js
  scripts/cli/tests/6_create_assets.js
  scripts/cli/tests/7_create_claim_compliance.js
  scripts/cli/tests/8_asset_transfer.js
Labels: merge-after-ci

#574 MESH-1236: `remove_authorization` payer => `authorized_by` (sometimes)
  pallets/identity/src/lib.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/testnet/src/fee_details.rs
Labels: merge-after-ci

#576 DEVOPS-211
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  rust-toolchain
Labels: concourse-test-devops211, merge-after-ci

#590 MESH-1252 & MESH-1253
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
  polymesh_schema.json
Labels: merge-after-ci

#591 MESH-1250: `on_runtime_upgrade`, clear V1 PIPs storage.
  pallets/pips/src/lib.rs
Labels: merge-after-ci

#592 MESH-1244: add `#[migrate_from($ty_old)]` form to `#[derive(Migrate)]`.
  primitives_derive/src/lib.rs
  primitives_derive/src/migrate.rs
Labels: merge-after-ci

#595 DEVOPS-174/purge-cache
  .concourse/pipelines/alcyone-commit.yaml
  .concourse/pipelines/alcyone-pull-request.yaml
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/master-commit.yaml
  .concourse/pipelines/master-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  .concourse/scripts/t-cargo-build.sh
  .concourse/scripts/t-cargo-test.sh
  .concourse/scripts/t-clippy-test.sh
  .concourse/scripts/t-npm-test.sh
Labels: merge-after-ci

#597 Removed staking fuzzer from workplace
  Cargo.lock
  Cargo.toml
Labels: merge-after-ci

#604 MESH-1243: add `migrate::migrate_double_map_keys`
  pallets/identity/src/lib.rs
  primitives/src/migrate.rs
Labels: merge-after-ci

#602 DEVOPS-232/move-polymesh-pipelines
  .concourse/pipelines/alcyone-commit.yaml
  .concourse/pipelines/alcyone-pull-request.yaml
  .concourse/pipelines/develop-commit.yaml
  .concourse/pipelines/develop-pull-request.yaml
  .concourse/pipelines/tooling-commit.yaml
  .concourse/pipelines/tooling-pull-request.yaml
  .concourse/scripts/t-cargo-build.sh
  .concourse/scripts/t-cargo-test.sh
  .concourse/scripts/t-clippy-test.sh
  .concourse/scripts/t-npm-install.sh
  .concourse/scripts/t-npm-test.sh
  .concourse/scripts/t-rustfmt-lint.sh
  .github/CODEOWNERS
Labels: merge-after-ci

#600 MESH-1257: Runtime upgrade functionality for CDD_ID.
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  primitives/src/condition.rs
  primitives/src/identity_claim.rs
  primitives/src/jurisdiction.rs
  primitives/src/migrate.rs
  primitives/src/proposition/valid_proof_of_investor.rs
  primitives_derive/src/lib.rs
  primitives_derive/src/migrate.rs
Labels: merge-after-ci

#606 MESH-1262: Infer `Proposer<_>` from `origin` on `Pips::propose`.
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/runtime/tests/src/storage.rs
  scripts/cli/tests/11_governance_management.js
Labels: breaking-api-changes, merge-after-ci

#611 Update max inflation from 20% to 14%
  pallets/runtime/develop/src/runtime.rs
Labels: merge-after-ci

#610 MESH-1141: Add 'PipsMetadata::transaction_version'
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
  polymesh_schema.json
Labels: merge-after-ci, storage-modification-changes

#618 polymesh_schema: add `Scheduled" variant to `ProposalState`
  polymesh_schema.json
Labels: merge-after-ci

#622 Schema: fix `Vote`'s definition due to changes
  polymesh_schema.json
Labels: merge-after-ci

#598 Mesh 1106/reserve currency ticker symbols on genesis
  Cargo.lock
  Cargo.toml
  pallets/asset/Cargo.toml
  pallets/asset/src/lib.rs
  pallets/common/src/constants.rs
  pallets/common/src/lib.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  src/chain_spec.rs
  src/data/currency_symbols.json
Labels: merge-after-ci

#621 `AssetIdentifier::isin`: remove allocation
  primitives/src/asset_identifier.rs
Labels: merge-after-ci

#603 Verify zk proof during claim addition
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/confidential_test.rs
  primitives/src/identity_claim.rs
  primitives/src/lib.rs
  primitives/src/proposition/mod.rs
  primitives/src/valid_proof_of_investor.rs
  scripts/fmt.sh
Labels: merge-after-ci

#624 MESH-1255/Transaction Payment: Pull in some substrate-rc6 changes
  Cargo.lock
  pallets/transaction-payment/Cargo.toml
  pallets/transaction-payment/src/lib.rs
Labels: merge-after-ci

#629 Use vector in settlement extrinsics
  pallets/basic-sto/src/lib.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/lib.rs
Labels: merge-after-ci

#638 `docs.yml`: switch branch to `develop`
  .github/workflows/docs.yml
Labels: merge-after-ci

#633 MESH-1273/ Skipping of changing slashing storage for nominators
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
  pallets/staking/src/slashing.rs
Labels: merge-after-ci

#635 MESH-1234: Allow GC to issue & revoke a CDD claim
  pallets/common/src/traits/identity.rs
  pallets/identity/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  src/chain_spec.rs
Labels: merge-after-ci

#608 Mesh 1072/ Track unique investor count & balances
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/common/src/traits/mod.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/cdd_offchain_worker/mock.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/statistics/src/lib.rs
Labels: merge-after-ci

#630 MESH-1277/ Add `add_investor_uniqueness_claim()` dispatchable
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/storage.rs
  polymesh_schema.json
  primitives/src/condition.rs
  primitives/src/identity_claim.rs
  primitives/src/valid_proof_of_investor.rs
Labels: merge-after-ci

#641 MESH-1251: Asset issuers can limit trusted issuers by claim type
  pallets/compliance-manager/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/settlement_test.rs
  polymesh_schema.json
  primitives/src/condition.rs
  primitives/src/identity_claim.rs
  primitives/src/lib.rs
  scripts/cli/util/init.js
Labels: breaking-api-changes, merge-after-ci, storage-modification-changes
