Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-02, with the labels that each got.

#822 MESH-1397 live queue pips benches + MESH-1395 + MESH-1507
  Cargo.lock
  pallets/pips/Cargo.toml
  pallets/pips/src/benchmarking.rs
  pallets/pips/src/lib.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/src/pallet_pips.rs
Labels: merge-after-ci

#891 MESH-1490: Checkpoint benchmarks
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/checkpoint/benchmarking.rs
  pallets/asset/src/checkpoint/mod.rs
  pallets/asset/src/lib.rs
  pallets/balances/src/benchmarking.rs
  pallets/committee/src/benchmarking.rs
  pallets/common/src/benchs/user.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/confidential/src/benchmarking.rs
  pallets/contracts/src/benchmarking.rs
  pallets/corporate-actions/src/ballot/benchmarking.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/identity/src/benchmarking.rs
  pallets/im-online/src/benchmarking.rs
  pallets/multisig/src/benchmarking.rs
  pallets/permissions/src/benchmarking.rs
  pallets/pips/src/benchmarking.rs
  pallets/portfolio/src/benchmarking.rs
  pallets/protocol-fee/src/benchmarking.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/benchmarking.rs
  pallets/sto/src/benchmarking.rs
  pallets/treasury/src/benchmarking.rs
  pallets/utility/src/benchmarking.rs
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_checkpoint.rs
  src/chain_spec.rs
Labels: merge-after-ci

#895 Override some default polkadot types
  polymesh_schema.json
  scripts/cli/package-lock.json
  scripts/cli/package.json
Labels: breaking-api-changes, merge-after-ci

#898 Moved asset types to polymesh-primitives
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/benchs/asset.rs
  pallets/common/src/traits/asset.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/confidential/src/benchmarking.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/statistics_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/statistics/src/benchmarking.rs
  polymesh_schema.json
  primitives/src/asset.rs
  primitives/src/lib.rs
Labels: merge-after-ci

#901 CircleCI changes
  .circleci/config.yml
  scripts/coverage.sh
Labels: merge-after-ci

#899 MESH-1531: Fix Checkpoint.timestamps into double map keyed by `Ticker`
  pallets/asset/src/checkpoint/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
Labels: breaking-api-changes, merge-after-ci, release-notes, storage-modification-changes

#905 Removed unnecessary constraints
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
Labels: merge-after-ci, release-notes

#894 MESH-1473/Create a list of transactions that require Asset/Portfolio permissions
  Cargo.lock
  Cargo.toml
  pallets/asset/src/checkpoint/mod.rs
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/settlement/src/lib.rs
  pallets/statistics/src/lib.rs
  pallets/sto/src/lib.rs
  utils/permissions/Cargo.toml
  utils/permissions/src/doc_parser/enums.rs
  utils/permissions/src/doc_parser/mod.rs
  utils/permissions/src/main.rs
Labels: merge-after-ci, release-notes

#903 Add modify window event and stop event to STO
  pallets/sto/src/benchmarking.rs
  pallets/sto/src/lib.rs
  polymesh_schema.json
  scripts/bd.sh
Labels: merge-after-ci, release-notes

#907 Added support for H2 tag perms
  utils/permissions/src/main.rs
Labels: merge-after-ci

#852 MESH-1379/permission logic integration test
  scripts/cli/tests/4_permission_management.js
  scripts/cli/util/init.js
Labels: merge-after-ci

#902 Script to simplify running JS integration tests
  scripts/cli/package.json
  scripts/cli/test.sh
  scripts/cli/tests/10_governance_management.js
  scripts/cli/tests/11_A_settlement.js
  scripts/cli/tests/11_B_settlement.js
  scripts/cli/tests/3_auth_join_did.js
  scripts/cli/tests/9_bridge_transfer.js
  scripts/cli/util/offchain_worker_test.js
  scripts/cli/yarn.lock
Labels: merge-after-ci

#909 Update Polymesh's subrtrate version to 2.0.1-2
  Cargo.lock
  Cargo.toml
  bin/bench/Cargo.toml
  bin/crypto-cli/Cargo.toml
  bin/executor/Cargo.toml
  bin/testing/Cargo.toml
  contracts/examples/custom-ink-env-types/Cargo.toml
  migration-tests/Cargo.toml
  migration-tests/remote-externalities/Cargo.toml
  node-rpc/Cargo.toml
  pallets/asset/Cargo.toml
  pallets/balances/Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/committee/Cargo.toml
  pallets/common/Cargo.toml
  pallets/compliance-manager/Cargo.toml
  pallets/confidential/Cargo.toml
  pallets/contracts/Cargo.toml
  pallets/corporate-actions/Cargo.toml
  pallets/group/Cargo.toml
  pallets/group/rpc/Cargo.toml
  pallets/group/rpc/runtime-api/Cargo.toml
  pallets/identity/Cargo.toml
  pallets/im-online/Cargo.toml
  pallets/multisig/Cargo.toml
  pallets/permissions/Cargo.toml
  pallets/pips/Cargo.toml
  pallets/portfolio/Cargo.toml
  pallets/protocol-fee/Cargo.toml
  pallets/protocol-fee/rpc/Cargo.toml
  pallets/protocol-fee/rpc/runtime-api/Cargo.toml
  pallets/runtime/build_tool/Cargo.toml
  pallets/runtime/common/Cargo.toml
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/extensions/Cargo.toml
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/tests/Cargo.toml
  pallets/settlement/Cargo.toml
  pallets/staking/Cargo.toml
  pallets/staking/rpc/Cargo.toml
  pallets/staking/rpc/runtime-api/Cargo.toml
  pallets/statistics/Cargo.toml
  pallets/sto/Cargo.toml
  pallets/sudo/Cargo.toml
  pallets/transaction-payment/Cargo.toml
  pallets/treasury/Cargo.toml
  pallets/utility/Cargo.toml
  pallets/weights/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/runtime-api/Cargo.toml
  src/service.rs
Labels: merge-after-ci

#917 MESH-1508, MESH-1469: Add Jurisdictions and clean up README.md
  README.md
  pallets/asset/src/lib.rs
  polymesh_schema.json
  primitives/src/jurisdiction.rs
Labels: merge-after-ci, release-notes

#918 Allow tipping for Operational TX from CDD/GC member
  Cargo.lock
  pallets/committee/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/transaction_payment_test.rs
  pallets/transaction-payment/Cargo.toml
  pallets/transaction-payment/src/lib.rs
Labels: merge-after-ci, release-notes

#921 MESH-1533/add minimum bond support to staking tests
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#922 MESH-1536: use substrate im-online pallet
  Cargo.lock
  Cargo.toml
  README.md
  bin/executor/Cargo.toml
  pallets/im-online/Cargo.toml
  pallets/im-online/src/benchmarking.rs
  pallets/im-online/src/lib.rs
  pallets/im-online/src/mock.rs
  pallets/im-online/src/tests.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/lib.rs
  pallets/runtime/mainnet/Cargo.toml
  pallets/runtime/mainnet/src/lib.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/lib.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/pallet_im_online.rs
  polymesh_schema.json
  src/chain_spec.rs
  src/service.rs
Labels: merge-after-ci

#924 MESH-1466: Nix live configs
  src/chain_spec.rs
  src/command.rs
Labels: merge-after-ci, release-notes

#923 Remove POC confidential pallet
  Cargo.lock
  Cargo.toml
  bin/executor/Cargo.toml
  pallets/common/Cargo.toml
  pallets/confidential/Cargo.toml
  pallets/confidential/src/benchmarking.rs
  pallets/confidential/src/lib.rs
  pallets/confidential/src/rng.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/mainnet/Cargo.toml
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/confidential_test.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_confidential.rs
  src/service.rs
Labels: merge-after-ci, release-notes

#920 New `polymesh_contracts::set_put_code_flag` extrinsic.
  pallets/contracts/src/benchmarking.rs
  pallets/contracts/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/contract_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/weights/src/polymesh_contracts.rs
Labels: merge-after-ci, release-notes

#925 MESH-1375: Fix module ordering + naming
  pallets/identity/src/lib.rs
  pallets/runtime/mainnet/src/runtime.rs
  pallets/statistics/src/lib.rs
Labels: breaking-api-changes, merge-after-ci, release-notes

#927 MESH-1558: Simplify & harden contract tests
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/contract_test.rs
Labels: merge-after-ci

#926 MESH-1556: allow distribution past dividend date
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
Labels: merge-after-ci, release-notes

#929 Mesh 713/reserve classic tickers
  pallets/asset/src/ethereum.rs
  src/chain_spec.rs
  src/data/reserved_classic_tickers.json
Labels: merge-after-ci

#941 Disabled extra CI tests
  .circleci/config.yml
Labels: merge-after-ci

#935 Update address prefix
  src/chain_spec.rs
Labels: merge-after-ci, release-notes

#937 Revert "MESH-1375: Fix module ordering + naming"
  pallets/identity/src/lib.rs
  pallets/runtime/mainnet/src/runtime.rs
  pallets/statistics/src/lib.rs
Labels: merge-after-ci
