Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-07, with the labels that each got.

#1039 Misc refactors and bug fixes, mostly re current DIDs
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/lib.rs
  pallets/protocol-fee/src/lib.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/group_test.rs
  pallets/runtime/tests/src/multisig.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/runtime/tests/src/treasury_test.rs
  pallets/treasury/src/lib.rs
  primitives/src/identity_claim.rs
Labels: release-notes

#1029 MESH-1615/Relax `CapitalDistribution::reclaim` to only require portfolio custody
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
Labels: release-notes

#1028 MESH-1629/create simple relayer
  Cargo.lock
  Cargo.toml
  README.md
  pallets/common/src/traits/mod.rs
  pallets/common/src/traits/relayer.rs
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/relayer/Cargo.toml
  pallets/relayer/src/benchmarking.rs
  pallets/relayer/src/lib.rs
  pallets/runtime/common/src/fee_details.rs
  pallets/runtime/common/src/runtime.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/itn/Cargo.toml
  pallets/runtime/itn/src/fee_details.rs
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/fee_details.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/relayer_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_relayer.rs
  polymesh_schema.json
  primitives/src/authorization.rs
Labels: release-notes

#1044 MESH-1651: Don't allow a portfolio with assets to be deleted
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/portfolio.rs
Labels: release-notes, storage-modification-changes

#1048 MESH-1625: Constant time portfolio name uniqueness
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/portfolio.rs
Labels: merge-after-ci, release-notes, storage-modification-changes

#1049 MESH-1625: Move out `AssetName` from `SecurityToken`
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/statistics_test.rs
  polymesh_schema.json
Labels: release-notes, storage-modification-changes

#1046 MESH-1631/redirect fees to subsidiser
  Cargo.lock
  pallets/common/src/traits/relayer.rs
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/protocol-fee/src/lib.rs
  pallets/relayer/Cargo.toml
  pallets/relayer/src/benchmarking.rs
  pallets/relayer/src/lib.rs
  pallets/runtime/common/src/runtime.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/transaction-payment/src/lib.rs
  primitives/src/lib.rs
Labels: release-notes

#1053 MESH-1625: Move out `CADetails` from `CorporateAction`
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/weights/src/pallet_asset.rs
  polymesh_schema.json
  primitives/src/asset.rs
  src/chain_spec.rs
Labels: release-notes, storage-modification-changes

#1059 MESH-1656/bridge freezing permissions
  pallets/bridge/src/lib.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/signed_extra.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
Labels: release-notes

#1057 MESH-1662/allow changing paying key
  pallets/relayer/src/lib.rs
  pallets/runtime/tests/src/relayer_test.rs
Labels: release-notes
