Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-05, with the labels that each got.

#986 MESH-1598/ use expect/assert in benchmarks
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/checkpoint/benchmarking.rs
  pallets/committee/src/benchmarking.rs
  pallets/common/src/benchs/asset.rs
  pallets/common/src/benchs/user_builder.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/contracts/src/benchmarking.rs
  pallets/corporate-actions/src/ballot/benchmarking.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/identity/src/benchmarking.rs
  pallets/multisig/src/benchmarking.rs
  pallets/permissions/src/benchmarking.rs
  pallets/pips/src/benchmarking.rs
  pallets/portfolio/src/benchmarking.rs
  pallets/runtime/develop/src/benchmarks/pallet_session.rs
  pallets/settlement/src/benchmarking.rs
  pallets/staking/src/benchmarking.rs
  pallets/statistics/src/benchmarking.rs
  pallets/sto/src/benchmarking.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#987 Fixed a bug preventing some operators from changing commission
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#989 Add ITN details to README
  README.md
Labels: merge-after-ci

#988 MESH-1593/Fix `payout_stakers` benchmarks
  pallets/staking/src/benchmarking.rs
  pallets/staking/src/lib.rs
  pallets/weights/src/pallet_staking.rs
Labels: merge-after-ci

#995 Add audit report
  README.md
  audit/Polymesh Audit - SRLabs.pdf
Labels: merge-after-ci

#990 MESH-1542/Improve code coverage for Identity module
  pallets/common/src/traits/identity.rs
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/weights/src/pallet_identity.rs
Labels: merge-after-ci

#966 MESH-1587: move Alcyone & general genesis identity balances to the bridge
  pallets/common/src/constants.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/contracts/src/benchmarking.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/settlement/src/benchmarking.rs
  primitives/src/identity_id.rs
  primitives/src/secondary_key.rs
  scripts/cli/tests/0_create_identities.js
  scripts/cli/tests/10_governance_management.js
  src/chain_spec.rs
  src/command.rs
  src/service.rs
Labels: merge-after-ci

#1006 Fix bug in primary key (PK) rotation
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/identity_test.rs
Labels: release-notes

#1004 MESH-1623/add memo field to portfolio
  pallets/common/src/traits/balances.rs
  pallets/common/src/traits/portfolio.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/portfolio/src/benchmarking.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/settlement_test.rs
  polymesh_schema.json
Labels: breaking-api-changes, merge-after-ci, release-notes, storage-modification-changes
