Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-01, with the labels that each got.

#815 MESH-1357: Test pips/staking interaction
  pallets/runtime/tests/src/staking/mod.rs
Labels: merge-after-ci

#832 Removed exemption pallet
  pallets/common/src/lib.rs
  pallets/common/src/traits/mod.rs
  pallets/runtime/common/src/exemption.rs
  pallets/runtime/common/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/storage.rs
Labels: merge-after-ci

#816 Add getter to retrieve all the exempted identities
  contracts/PercentageTransferManager/src/lib.rs
Labels: merge-after-ci, release-notes

#833 Remove duplicated schedule event and fix comments
  pallets/pips/src/lib.rs
Labels: merge-after-ci, release-notes

#821 Mesh 1373/ Configurable limit on no. of validators for an entity
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
  polymesh_schema.json
Labels: breaking-api-changes, release-notes, storage-modification-changes

#743 MESH-1294/Multisig benchmarks
  Cargo.lock
  pallets/bridge/src/lib.rs
  pallets/common/src/constants.rs
  pallets/common/src/traits/identity.rs
  pallets/identity/src/lib.rs
  pallets/multisig/Cargo.toml
  pallets/multisig/src/benchmarking.rs
  pallets/multisig/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/multisig.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/lib.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_multisig.rs
  scripts/test.sh
Labels: merge-after-ci, release-notes

#799 Mesh 1383/Settlement Benches
  Cargo.lock
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/benchs/user.rs
  pallets/common/src/traits/asset.rs
  pallets/compliance-manager/src/lib.rs
  pallets/contracts/fixtures/ptm.wat
  pallets/contracts/src/benchmarking.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/Cargo.toml
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  pallets/weights/src/pallet_settlement.rs
Labels: merge-after-ci, release-notes

#831 Misc cleanups & refactorings, Part 1
  pallets/asset/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/confidential/src/lib.rs
  pallets/contracts/src/lib.rs
  pallets/group/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/settlement/src/lib.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci, release-notes

#835 Update current identity when a key joins a new identity
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/identity_test.rs
Labels: merge-after-ci

#837 Misc cleanups & refactorings, Part 2
  Cargo.lock
  pallets/identity/Cargo.toml
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/permissions/src/lib.rs
  pallets/pips/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/protocol-fee/src/lib.rs
Labels: merge-after-ci, release-notes

#834 Fix PIA semantics and forwarded_call permissions
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/common/src/traits/compliance_manager.rs
  pallets/common/src/traits/identity.rs
  pallets/compliance-manager/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/identity/src/types.rs
  pallets/permissions/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/sto/src/lib.rs
  primitives/src/proposition/base.rs
  primitives/src/proposition/mod.rs
  primitives/src/valid_proof_of_investor.rs
Labels: merge-after-ci, release-notes

#841 MESH-1431/Allow fix rewards
  Cargo.lock
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/staking/inflation.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/Cargo.toml
  pallets/staking/src/inflation.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci, release-notes

#846 Allow ceiling multiplication in staking
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#845 Fix initialisation order and upgrade for PermissionedIdenities
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci

#843 Misc cleanups & refactorings, Part 3
  pallets/runtime/common/src/cdd_check.rs
  pallets/runtime/common/src/lib.rs
  pallets/settlement/src/lib.rs
  pallets/statistics/src/lib.rs
  pallets/sto/src/lib.rs
  pallets/transaction-payment/src/lib.rs
  pallets/treasury/src/lib.rs
  pallets/utility/src/lib.rs
  primitives/src/jurisdiction.rs
  primitives/src/lib.rs
Labels: merge-after-ci

#844 MESH-1448/Add schedule instruction weight
  pallets/settlement/src/lib.rs
Labels: merge-after-ci

#849 Re enable slashing
  pallets/staking/src/lib.rs
Labels: merge-after-ci, release-notes

#839 MESH-1418/Enforce cdd_id uniqueness
  pallets/common/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/staking/mod.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/benchmarking.rs
  primitives/src/cdd_id.rs
  primitives/src/identity_claim.rs
  primitives/src/proposition/base.rs
Labels: merge-after-ci, release-notes

#840 Refactored Multisig benchmarks
  pallets/multisig/src/benchmarking.rs
  pallets/multisig/src/lib.rs
  pallets/runtime/tests/src/multisig.rs
  pallets/weights/src/pallet_multisig.rs
  polymesh_schema.json
Labels: merge-after-ci, release-notes

#848 Mesh 1460/STO improvements
  Cargo.lock
  pallets/runtime/tests/src/sto_test.rs
  pallets/sto/Cargo.toml
  pallets/sto/src/lib.rs
  polymesh_schema.json
Labels: merge-after-ci, release-notes

#850 Minor cleanup
  pallets/multisig/src/lib.rs
Labels: merge-after-ci

#851 Fixed RPC definitions
  pallets/portfolio/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  polymesh_schema.json
  rpc/runtime-api/src/lib.rs
  rpc/runtime-api/src/portfolio.rs
  rpc/src/lib.rs
  rpc/src/portfolio.rs
Labels: breaking-api-changes, merge-after-ci, release-notes

#854 Mesh 1463/Documentation build fails
  pallets/bridge/Cargo.toml
  pallets/permissions/Cargo.toml
Labels: merge-after-ci

#771 MESH-1288 committee benchmarks
  Cargo.lock
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/common/src/benchs/user.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_committee.rs
Labels: merge-after-ci, release-notes

#828 Initial `make_asset` refactoring
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/benchs/asset.rs
  pallets/common/src/benchs/mod.rs
  pallets/common/src/traits/asset.rs
  pallets/compliance-manager/src/lib.rs
  pallets/confidential/src/lib.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/runtime/common/Cargo.toml
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/benchmarking.rs
  pallets/statistics/src/lib.rs
  pallets/sto/src/lib.rs
  pallets/weights/Cargo.toml
  rpc/runtime-api/src/compliance_manager.rs
Labels: merge-after-ci

#859 Mesh 1452/benchs failing
  Cargo.toml
  pallets/identity/Cargo.toml
  pallets/identity/src/benchmarking.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/benchmarking.rs
  pallets/runtime/develop/Cargo.toml
  pallets/statistics/Cargo.toml
  pallets/statistics/src/benchmarking.rs
Labels: merge-after-ci

#860 Helper CLI
  Cargo.lock
  Cargo.toml
  bin/crypto-cli/Cargo.toml
  bin/crypto-cli/README.md
  bin/crypto-cli/src/main.rs
Labels: merge-after-ci

#861 MESH-1468/Add sudo pallet
  .circleci/config.yml
  Cargo.lock
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/testnet/Cargo.toml
  pallets/sudo/Cargo.toml
  pallets/sudo/README.md
  pallets/sudo/src/lib.rs
  pallets/sudo/src/mock.rs
  pallets/sudo/src/tests.rs
Labels: merge-after-ci

#868 Fix initiate_corporate_action weight
  pallets/corporate-actions/src/lib.rs
Labels: merge-after-ci

#867 MESH-1461/Fix underflow/overflow bugs in Asset Identifier Validations
  primitives/src/asset_identifier.rs
Labels: merge-after-ci

#855 MESH-1453/Pass legs count in portfolio based extrinsics
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  pallets/sto/src/lib.rs
  scripts/cli/tests/12_A_settlement.js
  scripts/cli/tests/12_B_settlement.js
  scripts/cli/util/init.js
Labels: breaking-api-changes, merge-after-ci, release-notes

#865 Fix treasury rewards
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
Labels: merge-after-ci

#857 MESH-1456, MESH-1464, MESH-1459: In committee, nix `close` + only use dynamic threshold
  Cargo.lock
  pallets/committee/Cargo.toml
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/committee_test.rs
  pallets/runtime/tests/src/pips_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/src/pallet_committee.rs
  primitives/src/lib.rs
Labels: breaking-api-changes, merge-after-ci, release-notes

#873 Execute legs in order
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/lib.rs
Labels: merge-after-ci, release-notes

#869 Fixed minor bugs in sto
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci, release-notes

#880 `adjust_live_queue`: fix sort order bug
  pallets/pips/src/lib.rs
  pallets/runtime/tests/src/pips_test.rs
Labels: merge-after-ci

#882 MESH-1489 (CP schedule ref counting) + MESH-1488 (CP schedule expiry-after-ticks)
  pallets/asset/src/checkpoint.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  polymesh_schema.json
  primitives/src/migrate.rs
Labels: breaking-api-changes, merge-after-ci, release-notes, storage-modification-changes

#876 Wasm Builder as external crate
  Cargo.lock
  Cargo.toml
  pallets/runtime/build_tool/Cargo.toml
  pallets/runtime/build_tool/src/lib.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/build.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/build.rs
  primitives_derive/Cargo.toml
  src/chain_spec.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/prerequisites.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: merge-after-ci

#883 MESH-1446/ Fix Genesis config ordering
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
Labels: merge-after-ci

#890 Audit 6: Mitigate overflow
  pallets/contracts/src/lib.rs
Labels: merge-after-ci

#878 Allow receipt signers to invalidate receipts
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  pallets/weights/src/pallet_settlement.rs
Labels: merge-after-ci, release-notes

#887 Audit 8: Mitigate overflow
  pallets/multisig/src/lib.rs
Labels: merge-after-ci, release-notes

#892 Updated docs pipeline
  .github/workflows/docs.yml
Labels: merge-after-ci

#879 MESH-1251/ Expose controller transfer as an extrinsic
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/weights/src/pallet_asset.rs
Labels: concourse-test, merge-after-ci, release-notes

#889 Audit 7: Mitigate Overflow
  pallets/runtime/tests/src/sto_test.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci
