Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-06, with the labels that each got.

#1011 MESH-1620/refactor
  pallets/utility/src/lib.rs
Labels: merge-after-ci

#1012 ExternalAgents: Fix schema + `fn agent_permissions`
  pallets/external-agents/src/lib.rs
  polymesh_schema.json
  primitives/src/subset.rs
Labels: merge-after-ci, release-notes

#996 MESH-1619/Allow rescheduling failed Settlements
  Cargo.lock
  pallets/runtime/tests/src/settlement_test.rs
  pallets/settlement/Cargo.toml
  pallets/settlement/src/benchmarking.rs
  pallets/settlement/src/lib.rs
  pallets/weights/src/pallet_settlement.rs
  polymesh_schema.json
Labels: release-notes

#1003 MESH-1620/improve batch functions (EventCounts, ErrorAt)
  pallets/runtime/tests/src/utility_test.rs
  pallets/utility/src/lib.rs
  polymesh_schema.json
Labels: breaking-api-changes, release-notes

#1017 MESH-1637/SecondaryKeyPermissionsUpdated event emits new permissions in both params
  pallets/common/src/traits/identity.rs
  pallets/identity/src/lib.rs
Labels: release-notes

#1027 MESH-1642/Debug: Fuzz Settlement Tests
  pallets/runtime/tests/src/settlement_test.rs
Labels: merge-after-ci

#1021 MESH-1638/Add a reverse map to allow an easy lookup from IdentityId to list of assets for which the identity is an EA
  pallets/external-agents/src/lib.rs
  pallets/runtime/tests/src/external_agents_test.rs
  pallets/runtime/tests/src/sto_test.rs
  pallets/settlement/src/benchmarking.rs
Labels: release-notes

#1034 secondary_keys: improve readability
  primitives/src/secondary_key.rs
Labels: merge-after-ci

#1013 MESH-1588/Cleanup compliance manager tests using `a_token` and `basic_asset`
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/storage.rs
Labels: merge-after-ci

#1035 Authorization refactor; nix `accept_authorization` for explicit extrinsics
  Cargo.lock
  pallets/asset/Cargo.toml
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/common/src/traits/external_agents.rs
  pallets/common/src/traits/identity.rs
  pallets/common/src/traits/multisig.rs
  pallets/common/src/traits/portfolio.rs
  pallets/external-agents/src/benchmarking.rs
  pallets/external-agents/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/portfolio/src/benchmarking.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/external_agents_test.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/portfolio.rs
  pallets/runtime/tests/src/settlement_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/weights/src/pallet_external_agents.rs
  pallets/weights/src/pallet_portfolio.rs
  polymesh_schema.json
  primitives/src/authorization.rs
  scripts/bench.sh
Labels: breaking-api-changes, release-notes

#1040 NCBD-234 Fix cli integration tests
  polymesh_schema.json
  scripts/cli/alcyone-polymesh.json
  scripts/cli/environment.config.js
  scripts/cli/package-lock.json
  scripts/cli/package.json
  scripts/cli/src/helpers/asset_helper.ts
  scripts/cli/src/helpers/bridge_helper.ts
  scripts/cli/src/helpers/committee_helper.ts
  scripts/cli/src/helpers/identity_helper.ts
  scripts/cli/src/helpers/key_management_helper.ts
  scripts/cli/src/helpers/permission_helper.ts
  scripts/cli/src/helpers/portfolio_helper.ts
  scripts/cli/src/helpers/settlement_helper.ts
  scripts/cli/src/interfaces/augment-api-consts.ts
  scripts/cli/src/interfaces/augment-api-errors.ts
  scripts/cli/src/interfaces/augment-api-events.ts
  scripts/cli/src/interfaces/augment-api-query.ts
  scripts/cli/src/interfaces/augment-api-rpc.ts
  scripts/cli/src/interfaces/augment-api-tx.ts
  scripts/cli/src/interfaces/augment-types.ts
  scripts/cli/src/interfaces/default/types.ts
  scripts/cli/src/interfaces/definitions.ts
  scripts/cli/src/tests/0_create_identities.ts
  scripts/cli/src/tests/10_governance_management.ts
  scripts/cli/src/tests/11_A_settlement.ts
  scripts/cli/src/tests/11_B_settlement.ts
  scripts/cli/src/tests/1_poly_transfer.ts
  scripts/cli/src/tests/2_key_management.ts
  scripts/cli/src/tests/3_auth_join_did.ts
  scripts/cli/src/tests/4_permission_management.ts
  scripts/cli/src/tests/5_claim_management.ts
  scripts/cli/src/tests/6_create_assets.ts
  scripts/cli/src/tests/7_create_claim_compliance.ts
  scripts/cli/src/tests/8_asset_minting.ts
  scripts/cli/src/tests/9_bridge_transfer.ts
  scripts/cli/src/types.ts
  scripts/cli/src/util/init.ts
  scripts/cli/tsconfig.json
  scripts/cli/yarn.lock
  src/chain_spec.rs
Labels: bug
