Repository PolymeshAssociation/Polymesh, pull requests merged in 2021-03, with the labels that each got.

#934 Revert "Mesh 1400/update storage hashers (#796)"
  pallets/asset/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/corporate-actions/src/ballot/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#943 Minor refactoring
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/utility/src/lib.rs
Labels: merge-after-ci

#940 Mesh 1535: New TestUtils pallet
  Cargo.lock
  Cargo.toml
  pallets/asset/src/benchmarking.rs
  pallets/asset/src/checkpoint/benchmarking.rs
  pallets/balances/src/benchmarking.rs
  pallets/committee/src/benchmarking.rs
  pallets/common/src/benchs/mod.rs
  pallets/common/src/benchs/user_builder.rs
  pallets/common/src/lib.rs
  pallets/common/src/traits/identity.rs
  pallets/common/src/traits/mod.rs
  pallets/compliance-manager/src/benchmarking.rs
  pallets/contracts/src/benchmarking.rs
  pallets/corporate-actions/src/ballot/benchmarking.rs
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/group/src/benchmarking.rs
  pallets/identity/src/benchmarking.rs
  pallets/identity/src/lib.rs
  pallets/multisig/src/benchmarking.rs
  pallets/pips/src/benchmarking.rs
  pallets/portfolio/src/benchmarking.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/benchmarks/pallet_session.rs
  pallets/runtime/develop/src/fee_details.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/mainnet/src/fee_details.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/fee_details.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/balances_test.rs
  pallets/runtime/tests/src/fee_details.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/src/benchmarking.rs
  pallets/staking/src/benchmarking.rs
  pallets/staking/src/testing_utils.rs
  pallets/statistics/src/benchmarking.rs
  pallets/sto/src/benchmarking.rs
  pallets/test-utils/Cargo.toml
  pallets/test-utils/src/benchmarking.rs
  pallets/test-utils/src/lib.rs
  pallets/treasury/src/benchmarking.rs
  pallets/utility/src/benchmarking.rs
  pallets/weights/Cargo.toml
  pallets/weights/src/lib.rs
  pallets/weights/src/pallet_identity.rs
  pallets/weights/src/pallet_test_utils.rs
  primitives/Cargo.toml
Labels: merge-after-ci, release-notes

#946 Fix validator running count
  pallets/runtime/tests/src/staking/mod.rs
  pallets/staking/src/lib.rs
Labels: merge-after-ci, release-notes

#936 Added use for ethereum types
  pallets/asset/src/lib.rs
Labels: merge-after-ci

#942 Capital Distributions: Use 'per_share' concept instead of total supply
  pallets/corporate-actions/src/benchmarking.rs
  pallets/corporate-actions/src/distribution/benchmarking.rs
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/corporate-actions/src/lib.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  polymesh_schema.json
Labels: breaking-api-changes, merge-after-ci, release-notes

#938 Asset::{create_asset, update_identifiers} now rejects bad `AssetIdentifiers`
  pallets/asset/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/storage.rs
  primitives/src/asset_identifier.rs
  primitives/src/smart_extension.rs
Labels: merge-after-ci, release-notes

#950 Update config params for mainnet
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/mainnet/src/constants.rs
  pallets/runtime/mainnet/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/settlement/src/lib.rs
  src/chain_spec.rs
Labels: merge-after-ci

#931 MESH-1530: bridge transactions complete in genesis
  pallets/bridge/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/contract_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/signed_extra.rs
  pallets/runtime/tests/src/staking/mock.rs
  primitives/src/identity_id.rs
  src/chain_spec.rs
Labels: merge-after-ci, release-notes

#928 MESH-1408/Refactor canTransfer to return all Results
  Cargo.lock
  pallets/asset/src/lib.rs
  pallets/common/src/traits/compliance_manager.rs
  pallets/compliance-manager/src/lib.rs
  pallets/portfolio/src/lib.rs
  pallets/runtime/common/src/runtime.rs
  pallets/runtime/tests/src/compliance_manager_test.rs
  pallets/runtime/tests/src/statistics_test.rs
  pallets/settlement/src/benchmarking.rs
  pallets/statistics/src/lib.rs
  polymesh_schema.json
  primitives/Cargo.toml
  primitives/src/asset.rs
  primitives/src/cdd_id.rs
  primitives/src/compliance_manager.rs
  primitives/src/condition.rs
  primitives/src/identity_claim.rs
  primitives/src/identity_id.rs
  primitives/src/jurisdiction.rs
  primitives/src/lib.rs
  primitives/src/statistics.rs
  rpc/runtime-api/src/asset.rs
  rpc/runtime-api/src/compliance_manager.rs
  rpc/src/asset.rs
  rpc/src/compliance_manager.rs
Labels: merge-after-ci, release-notes

#930 Mesh 1541/clean up asset and code coverage
  pallets/asset/src/checkpoint/mod.rs
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/bridge.rs
  pallets/runtime/tests/src/contract_test.rs
  pallets/runtime/tests/src/ext_builder.rs
  pallets/runtime/tests/src/lib.rs
  pallets/runtime/tests/src/signed_extra.rs
  pallets/runtime/tests/src/staking/mock.rs
  primitives/src/identity_id.rs
  src/chain_spec.rs
Labels: merge-after-ci

#956 Added stablecoins as an asset type
  polymesh_schema.json
  primitives/src/asset.rs
Labels: merge-after-ci

#955 Mesh 1570/clean old scope_id
  pallets/asset/src/lib.rs
  pallets/common/src/traits/asset.rs
  pallets/identity/src/lib.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/identity_test.rs
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  primitives/src/cdd_id.rs
Labels: merge-after-ci

#958 Added identity to staking `Reward` event
  pallets/staking/src/lib.rs
Labels: merge-after-ci, release-notes

#957 MESH-1592: balance_at RPC
  pallets/runtime/common/src/runtime.rs
  polymesh_schema.json
  rpc/runtime-api/src/asset.rs
  rpc/runtime-api/src/pips.rs
  rpc/src/asset.rs
  rpc/src/pips.rs
Labels: merge-after-ci, release-notes

#960 MESH-1544: pips RPC tests
  pallets/runtime/tests/src/pips_test.rs
Labels: merge-after-ci

#961 Make alcyone the default network
  src/command.rs
Labels: merge-after-ci

#959 MESH-1589: Limit lengths
  Cargo.lock
  Cargo.toml
  pallets/asset/Cargo.toml
  pallets/asset/src/lib.rs
  pallets/base/Cargo.toml
  pallets/base/src/lib.rs
  pallets/bridge/Cargo.toml
  pallets/bridge/src/lib.rs
  pallets/common/src/lib.rs
  pallets/common/src/traits/identity.rs
  pallets/common/src/traits/mod.rs
  pallets/compliance-manager/Cargo.toml
  pallets/compliance-manager/src/lib.rs
  pallets/contracts/Cargo.toml
  pallets/contracts/src/lib.rs
  pallets/corporate-actions/Cargo.toml
  pallets/corporate-actions/src/ballot/mod.rs
  pallets/identity/Cargo.toml
  pallets/identity/src/lib.rs
  pallets/pips/Cargo.toml
  pallets/pips/src/lib.rs
  pallets/portfolio/Cargo.toml
  pallets/portfolio/src/lib.rs
  pallets/runtime/common/src/runtime.rs
  pallets/runtime/develop/Cargo.toml
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/itn/Cargo.toml
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/testnet/Cargo.toml
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/Cargo.toml
  pallets/runtime/tests/src/staking/mock.rs
  pallets/runtime/tests/src/storage.rs
  pallets/settlement/Cargo.toml
  pallets/settlement/src/lib.rs
  pallets/sto/Cargo.toml
  pallets/sto/src/lib.rs
  primitives/src/compliance_manager.rs
  primitives/src/condition.rs
Labels: merge-after-ci, release-notes

#971 Fixed cargo.lock
  Cargo.lock
Labels: merge-after-ci

#963 MESH-1545/Improve STO code coverage
  pallets/runtime/tests/src/sto_test.rs
  pallets/sto/src/lib.rs
Labels: merge-after-ci

#976 MESH-1602: Unset PortfolioCustodian if the new custodian is the portfolio owner
  pallets/portfolio/src/lib.rs
  pallets/runtime/tests/src/portfolio.rs
Labels: merge-after-ci, release-notes

#975 transfer_benefit: fix 'remaining' underflow
  pallets/corporate-actions/src/distribution/mod.rs
  pallets/runtime/tests/src/corporate_actions_test.rs
Labels: merge-after-ci, release-notes

#972 Expose constants in metadata
  pallets/asset/src/lib.rs
  pallets/balances/src/lib.rs
  pallets/base/src/lib.rs
  pallets/compliance-manager/src/lib.rs
  pallets/corporate-actions/src/lib.rs
  pallets/identity/src/lib.rs
  pallets/runtime/common/src/runtime.rs
  pallets/runtime/develop/src/runtime.rs
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/testnet/src/runtime.rs
  pallets/runtime/tests/src/asset_test.rs
  pallets/runtime/tests/src/storage.rs
  pallets/staking/src/lib.rs
  pallets/statistics/src/lib.rs
Labels: merge-after-ci, release-notes

#973 Minor GC related fixes
  pallets/identity/src/lib.rs
  pallets/runtime/itn/src/runtime.rs
  pallets/runtime/tests/src/identity_test.rs
Labels: merge-after-ci
